# Generated by Django 5.1.7 on 2025-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Default Title', max_length=225),
        ),
    ]
